# Generated by Django 2.2.2 on 2019-07-14 17:15

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('assetid', models.CharField(default=api.models.get_uuid, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('assetname', models.CharField(max_length=255)),
                ('date_of_purchase', models.DateField()),
                ('price', models.FloatField()),
                ('date_of_last_maintainence', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('workerid', models.CharField(default=api.models.get_uuid, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('workername', models.CharField(max_length=255)),
                ('worker_address', models.TextField()),
                ('join_date', models.DateField()),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskid', models.CharField(default=api.models.get_uuid, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('taskname', models.CharField(max_length=255)),
                ('task_description', models.TextField()),
                ('time_of_allocation', models.DateTimeField()),
                ('time_to_be_performed_by', models.DateTimeField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Asset')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Worker')),
            ],
        ),
    ]
