# Generated by Django 2.2.2 on 2019-07-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190715_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_of_allocation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
